name: Create PR for Protocol Submissions
on:
  push:
    branches: [auto-submissions]
    paths: ['staging/**/*.yml']

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-submissions
          base: main
          title: "Protocol submission for review"
          body: |
            ## New Protocol Submission

            **Submitted via:** bf_standards() function

            ### Review Checklist
            - [ ] Protocol follows naming conventions (underscores, descriptive)
            - [ ] Examples are realistic and comprehensive
            - [ ] Documentation is clear and complete
            - [ ] Bit allocation is appropriate for data range
            - [ ] Function handles edge cases properly (NA values, extremes)
            - [ ] Description uses systematic glue syntax
            - [ ] Protocol is atomic (single concept)
            - [ ] Version number and change description are appropriate

            **Note:** Protocol will be automatically moved to final location upon merge.
          delete-branch: false
